networks:
  meteorcloud:
    name: meteorcloud

services:
  console:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.console.dev
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000}
      VITE_DOCS_BASE_URL: ${VITE_DOCS_BASE_URL:-http://localhost:3000/docs}
    ports:
      - "5173:5173"
    networks:
      - meteorcloud
